---
version: '3.4'

volumes:
  mssql-data:
  oracle-data:
  portainer-data:

services:

  healthcheck:
    image: nginx:1.23.3
    platform: linux/amd64
    volumes:
    - ./index.html:/usr/share/nginx/html/index.html
    environment:
      ENV: development
    ports:
    - 8080:80
    networks:
    - customernetwork

networks:
    customernetwork: