---
version: '3.4'

volumes:
  mssql-data:
  oracle-data:
  data-bridge:
  portainer-data:

services:

  healthcheck:
    image: nginx:alpine-slim
    platform: linux/amd64
    volumes:
    - ./index.html:/usr/share/nginx/html/index.html
    ports:
    - 80:80
    networks:
    - customernetwork

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWRD: Passw0rd_
    volumes:
     - mssql-data:/var/opt/mssql
    ports:
    - 1443:1443
    networks:
    - customernetwork

  mssql-tools:
    image: mcr.microsoft.com/mssql-tools
    platform: linux/amd64
    container_name: mssql-tools
    networks:
    - customernetwork

  oracledb:
    # shm_size: 1g
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracledb
    platform: linux/amd64
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
    environment:
      - ORACLE_SID=XE
      - ORACLE_PDB=test
      - ORACLE_PWD=test
    volumes:
      - oracle-data:/opt/oracle/oradata
      - data-bridge:/data-bridge
      - ./initscripts:/u01/app/oracle/scripts/startup # please here init scripts
    networks:
      - customernetwork

  portainer:
    image: portainer/portainer-ce:2.17.0-alpine
    platform: linux/amd64
    container_name: portainer
    restart: always
    command: --admin-password '$$2a$$12$$y9I7GSbLoe5HtSe9Y5KmO.ZbGp1.WYIa8mPJWaztY9IUOH9wNBqCC'
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
    ports:
      - 9000:9000
    networks:
      - customernetwork

networks:
    customernetwork: